apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::135808959960:role/eksctl-naveenrajoli-nodegroup-expe-NodeInstanceRole-TOiK1ZrUphOQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::135808959960:user/eksdescribenaveen
      username: eksdescribenaveen
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-25T05:27:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1385"
  uid: 2b0e3f65-0755-4f04-8c37-1b0e8a4bfb0b
